version: "3"

services:
  inference:
    image: photon_server:v1
    networks:
      backend:
          ipv4_address: 172.28.1.1
  endpoint:
    image: shine_aibe:v1.3.1
    links:
      - "inference: inf"
    ports:
      - "5001:80"
    networks:
      backend:
          ipv4_address: 172.28.1.2

networks:
  backend:
    ipam:
      driver: default
      config:
        - subeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Nzc2NTIwNjUsImlhdCI6MTY3NzY1MTc2NSwibmJmIjoxNjc3NjUxNzY1LCJpZGVudGl0eSI6MX0.W2xxwez1rJe0whKDqpLTRO_R3VFk5yUys6TVZlHqnzonet: 172.28.0.0/16